config/routes.rb
Teleroster31::Application.routes.draw do
	
  resources :employees
  root :to => "employees#index"	

end

app/models/employee.rb
class Employee < ActiveRecord::Base
	self.table_name = "MODAEmployee"
	attr_accessible :firstname, :lastname, :phoneextension,:businessphone, :DeskNumber
	
	def self.search(search)
		if search
		  if search =~ /\w+\s\w+/i
		  	where('FirstName LIKE ? AND LastName LIKE ? OR FirstName LIKE ?', "%#{search.split(' ')[0]}%", "%#{search.split(' ')[1]}%", "%#{search}%")     	
		  else
		    where('FirstName LIKE ? OR LastName LIKE ? OR PhoneExtension LIKE ? OR BusinessPhone LIKE ? OR DeskNumber LIKE ? OR Department LIKE ? OR Title LIKE ? OR Cell LIKE ?', "%#{search}%", "%#{search}%", "%#{search}%", "%#{search}%", "%#{search}%", "%#{search}%", "%#{search}%", "%#{search}%")
		  end
		else
		  scoped
		end
	end 
	
	def self.quicksearch(search)
		if search
		  if search =~ /\w+\s\w+/i
		  	where('FirstName LIKE ? AND LastName LIKE ? OR FirstName LIKE ?', "%#{search.split(' ')[0]}%", "%#{search.split(' ')[1]}%", "%#{search}%")     	
		  else
		    where('FirstName LIKE ? OR LastName LIKE ? OR PhoneExtension LIKE ? OR BusinessPhone LIKE ? OR DeskNumber LIKE ?' , "%#{search}%","%#{search}%", "%#{search}%", "%#{search}%", "%#{search}%")
		  end
		else
		  scoped
		end
	end 	
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/employees_controller.rb
class EmployeesController < ApplicationController
  helper_method :sort_column, :sort_direction
  
  def index
	if request.user_agent.include?("iPhone")
		@employees = Employee.where('LastName IS NOT NULL').quicksearch(params[:search]).order(sort_column + " " + sort_direction).page(params[:page]).per(8)	
	else
		@employees = Employee.where('LastName IS NOT NULL').search(params[:search]).order(sort_column + " " + sort_direction).page(params[:page]).per(10)	
        @searchcounts = Employee.where('LastName IS NOT NULL').search(params[:search]).size		
	end    
  end
  
  private
  
  def sort_column
    Employee.column_names.include?(params[:sort]) ? params[:sort] : "LastName"
  end
  
  def sort_direction
    %w[asc desc].include?(params[:direction]) ? params[:direction] : "asc"
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def sortable(column, title = nil)
    title ||= column.titleize
    css_class = column == sort_column ? "current #{sort_direction}" : nil
    direction = column == sort_column && sort_direction == "asc" ? "desc" : "asc"
    link_to title, params.merge(:sort => column, :direction => direction, :page => nil), {:class => css_class}
  end
end

app/helpers/employees_helper.rb
module EmployeesHelper
end

app/helpers/error_messages_helper.rb
module ErrorMessagesHelper
  # Render error messages for the given objects. The :message and :header_message options are allowed.
  def error_messages_for(*objects)
    options = objects.extract_options! 
    options[:header_message] ||= "Invalid Fields"
    options[:message] ||= "Correct the following errors and try again."
    messages = objects.compact.map { |o| o.errors.full_messages }.flatten
    unless messages.empty?
      content_tag(:div, :class => "error_messages") do
        list_items = messages.map { |msg| content_tag(:li, msg) }
        content_tag(:h2, options[:header_message]) + content_tag(:p, options[:message]) + content_tag(:ul, list_items.join.html_safe)
      end
    end
  end
  
  module FormBuilderAdditions
    def error_messages(options = {})
      @template.error_messages_for(@object, options)
    end
  end
end

ActionView::Helpers::FormBuilder.send(:include, ErrorMessagesHelper::FormBuilderAdditions)

app/helpers/layout_helper.rb
# These helper methods can be called in your template to set variables to be used in the layout
# This module should be included in all views globally,
# to do so you may need to add this line to your ApplicationController
#   helper :layout
module LayoutHelper
	def title(page_title, show_title = true)
	content_for(:title) { page_title.to_s }
	@show_title = show_title
	end
	
	def show_title?
	@show_title
	end
	
	def stylesheet(*args)
	content_for(:head) { stylesheet_link_tag(*args) }
	end
	
	def javascript(*args)
	content_for(:head) { javascript_include_tag(*args) }
	end
  
  	def data_anniversary
		a = []
		n = 0
		(1976..Time.new.year).each do |y|
		  n = Employee.where('year(Anniversary) = ?', y ).size
		  a.push(n)	
		end
		return a
	end  
	
	def data_location	
	  a = []	
	  a = Employee.select("Location").where('Location is not null').group("Location").count.delete_if {|key, value| key == "ODS" }.to_a.sort
	  return a
	end   
	
	def data_department	
	  a = []	
	  a = Employee.select("Department").where('Department is not null').group("Department").count.delete_if {|key, value| key == "ODS" }.to_a.sort
	  return a
	end  
	
	def total_employees
	  a = Employee.where('firstname is not null').count.to_s
	end
  
end

app/views/employees/_employees.html.erb
<%= hidden_field_tag :direction, params[:direction] %>
<%= hidden_field_tag :sort, params[:sort] %>


<p><b>Count: <%= @searchcounts %></b></p>

<p><b style="float:right"><%= paginate @employees %></b></p>

<table class="pretty">
  <tr>
    <th><%= sortable "FirstName" %></th>
    <th><%= sortable "LastName" %></th>
    <th><%= sortable "PhoneExtension" %></th>
    <th><%= sortable "BusinessPhone" %></th>
    <th><%= sortable "DeskNumber" %></th>
    <th><%= sortable "Department" %></th>   
    <th><%= sortable "Title" %></th>
    <th><%= sortable "SupervisorName" %></th>       
    <th><%= sortable "Cell" %></th>     
    <th><%= "Picture" %></th>         
  </tr>
  <% for employee in @employees %>
    <tr>
      <td><%= employee.FirstName %></td>
      <td><%= employee.LastName %></td>
      <td><%= employee.PhoneExtension %></td>
      <td><%= employee.BusinessPhone %></td>
      <td><%= employee.DeskNumber %></td>
      <td><%= employee.Department %></td>    
      <td><%= employee.Title %></td>
      <td><%= employee.SupervisorName %></td>             
      <td><%= employee.Cell %></td>   
      <% if not employee.thumbnailPhoto.nil? %>  
	    <td><%= ('<img src="data:image/jpg;base64,%s" height="50" width="50">' % Base64.encode64(employee.thumbnailPhoto||"rails.png")).html_safe %></td>  
	  <% else %>  
	    <td><%= image_tag("moda_logo.png") %> </td>
	  <% end %>     
    </tr>
  <% end %>
</table>

<b><%= paginate @employees %></b>

app/views/employees/_employeesiphone.html.erb
<%= hidden_field_tag :direction, params[:direction] %>
<%= hidden_field_tag :sort, params[:sort] %>

<table class="pretty">
  <tr>
    <th><%= sortable "FirstName" %></th>
    <th><%= sortable "LastName" %></th>
    <th><%= sortable "PhoneExtension" %></th>
    <th><%= sortable "DeskNumber" %></th>
  </tr>
  <% for employee in @employees %>
    <tr>
      <td><%= employee.FirstName %></td>
      <td><%= employee.LastName %></td>
      <td id="extension">
      	<% if employee.Cell.nil? %>
      	  <%= employee.PhoneExtension %> 
      	<% elsif employee.Cell.size > 4 %>
      	  <%= employee.PhoneExtension + " Cell: " %>
      	  <br>
      	  <a href= <%= "&#34;tel:#{employee.Cell}&#34;".html_safe %>><%= employee.Cell %> </a>
      	<%else%>  
      	  <%= employee.PhoneExtension %>       	   	
      	<% end %>
  	  </td>
      <td><%= employee.DeskNumber %></td>      
    </tr>
  <% end %>
</table>

<%= paginate @employees %>

app/views/employees/index.html.erb
<%= form_tag employees_path, :method => 'get', remote: true, :id => "employees_search" do %>

  <% if request.user_agent.include?("iPhone") %>
  <div id="box">
    <div id="inputfield"><b id="searchlable">Search</b><%= text_field_tag :search, params[:search] %></div><b>
  </div>  
    <div id="iphone"><%= render 'employeesiphone' %></div>  

  <% else %>
    <p>
      <b>Search</b> <%= text_field_tag :search, params[:search] %> 
    </p>  
    <div id="employees"><%= render 'employees' %></div>  
  <%end%>
  

<% end %>            

app/views/employees/index.js.erb
  <% if request.user_agent.include?("iPhone") %>
  	$("#iphone").html("<%= escape_javascript(render("employeesiphone")) %>"); 
  <% else %>
  	$("#employees").html("<%= escape_javascript(render("employees")) %>");
  <%end%>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
  	<link rel="apple-touch-icon" href="/assets/odslogo.png" />
    <title>ODS Employee Quick Search</title>

    <%= javascript_include_tag "defaults" %>
    <%= csrf_meta_tag %>
    <%= yield(:head) %>
    
    <% if request.user_agent.include?("iPhone") %>
    	<%= stylesheet_link_tag "iphone" %>
   		<meta name="viewport" content="width=device-width; initial-scale=1.0; maximum-scale=1.0; user-scalable=0;" />
   <% else %>
      	<%= stylesheet_link_tag "application" %>
   <% end %>
  </head>
  <body>
    <div id="container">
      <% flash.each do |name, msg| %>
        <%= content_tag :div, msg, :id => "flash_#{name}" %>
      <% end %>
      <%= content_tag :h1, yield(:title) if show_title? %>
      <%= yield %>
    </div>
  </body>
</html>